# Generated by Django 5.1.3 on 2024-12-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.CharField(blank=True, default='8178e420-a7a5-4e7d-9651-a90de78d9879', max_length=40, primary_key=True, serialize=False)),
                ('judul', models.CharField(default='', max_length=100, verbose_name='Nama Buku')),
                ('pengarang', models.CharField(default='', max_length=100, verbose_name='Pengarang Buku')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Harga Buku')),
                ('isbn', models.CharField(default='', max_length=50, verbose_name='Kode ISBN')),
                ('halaman', models.PositiveIntegerField(default=0, verbose_name='Jumlah Halaman')),
                ('deskripsi', models.TextField(default='', verbose_name='Deskripsi Singkat')),
                ('point', models.PositiveIntegerField(default=0, verbose_name='Point')),
                ('tipe', models.CharField(choices=[('free', 'free'), ('subscribe', 'subscribe'), ('buy', 'buy')], default='', max_length=20)),
                ('pdf_full', models.FileField(upload_to='pdf_full', verbose_name='File PDF Full')),
                ('pdf_prev', models.FileField(upload_to='pdf_prev', verbose_name='File PDF Preview')),
                ('kategori', models.CharField(choices=[('PA', 'PA'), ('Pemuridan', 'Pemuridan')], max_length=20)),
                ('view', models.PositiveBigIntegerField(default=0)),
                ('is_update_prev', models.BooleanField(blank=True, default=False, verbose_name='IS UPDATE PDF PREVIEW?')),
                ('is_update_full', models.BooleanField(blank=True, default=False, verbose_name='IS UPDATE PDF FULL?')),
                ('is_new', models.BooleanField(blank=True, default=False, verbose_name='IS CREATE NEW?')),
            ],
        ),
        migrations.CreateModel(
            name='BooksFullJPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literatur.books'))),
                ('id_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literatur.books')),
            ],
        ),
        migrations.CreateModel(
            name='BooksPrevJPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literatur.books'))),
                ('id_books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literatur.books')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perkantas', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Data Perkantas')),
                ('alias', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nama Panggilan')),
                ('nama_lengkap', models.CharField(blank=True, max_length=200, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('total_poin', models.PositiveSmallIntegerField(default=0)),
                ('total_book', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.PositiveSmallIntegerField(default=0)),
                ('booked_date', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(choices=[('BCA', 'BCA'), ('Mandiri', 'Mandiri')], max_length=20)),
                ('payment_code', models.CharField(blank=True, max_length=100, null=True)),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='literatur.books')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='literatur.userdetail')),
            ],
            options={
                'unique_together': {('id_book', 'id_user')},
            },
        ),
        migrations.CreateModel(
            name='customerBookmark',
            fields=[
                ('id_bookmark', models.CharField(blank=True, default='f580d155-d01d-4ca3-bea1-7aa6222e61d9', max_length=36, primary_key=True, serialize=False)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('blue', 'blue'), ('red', 'red'), ('yellow', 'yellow'), ('green', 'green'), ('chocolate', 'chocolate'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('purple', 'purple'), ('violet', 'violet'), ('grey', 'grey')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=2000, null=True)),
                ('is_penting', models.BooleanField(default=False)),
                ('id_userbook', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='literatur.userbook')),
            ],
            options={
                'unique_together': {('page', 'id_userbook')},
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.CharField(default='19982dea-47a1-49b2-952e-abad67e7587e', max_length=36, primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=200)),
                ('updated_review', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('id_buku', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='id_buku', to='literatur.books')),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='literatur.userdetail')),
            ],
            options={
                'unique_together': {('id_buku', 'id_customer')},
            },
        ),
    ]
