# Generated by Django 5.1.3 on 2024-12-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='books',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='is_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='books',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='id',
            field=models.CharField(default='26fc38f9-b877-4454-9a49-c334918fd4fb', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.CharField(blank=True, default='c04f3fb1-14a9-4fa0-bbfe-073d402ac4ab', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='id_bookmark',
            field=models.CharField(blank=True, default='73d5cc4b-4a3c-4b3e-ac6a-9dd9deb22d42', max_length=36, primary_key=True, serialize=False),
        ),
    ]
