# Generated by Django 5.1.3 on 2024-12-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0002_books_discount_books_is_bestseller_books_is_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerbookmark',
            name='id_bookmark',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
