# Generated by Django 5.1.3 on 2024-12-07 01:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0003_userdetail_id_customer_alter_bookreview_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereview',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_customer',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('9faeb376-decd-4e3c-b781-bb848ee6ca37'), editable=False),
        ),
    ]
