# Generated by Django 5.1.3 on 2024-12-07 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0004_pagereview_is_active_alter_userdetail_id_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereview',
            name='star',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_customer',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('090a1c37-87ec-415c-a568-1f61a1f20e74'), editable=False),
        ),
    ]
