# Generated by Django 5.1.3 on 2024-12-07 02:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0005_pagereview_star_alter_userdetail_id_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagereview',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('26d07bbb-1cb0-4bcb-81af-ecc686c1b8dc'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_customer',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('906a4d3f-ef37-4ca6-9c9d-18840021b814'), editable=False),
        ),
    ]
