# Generated by Django 5.1.3 on 2024-12-07 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0006_alter_pagereview_id_alter_userdetail_id_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagereview',
            name='star',
        ),
        migrations.AlterField(
            model_name='pagereview',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('88b98fbb-6d10-46e4-8b02-c3cfc0deb611'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_customer',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('84bf4901-50fd-452f-b8fb-4ea4f9fb4ff1'), editable=False),
        ),
    ]
