# Generated by Django 5.1.3 on 2024-12-07 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0007_remove_pagereview_star_alter_pagereview_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagereview',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='id_customer',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
