# Generated by Django 5.1.4 on 2024-12-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0008_alter_pagereview_id_alter_userdetail_id_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=30)),
                ('keterangan', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='literatur.category'),
        ),
    ]
