# Generated by Django 5.1.4 on 2024-12-09 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0010_alter_books_id_alter_books_pdf_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_update_full',
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_update_prev',
        ),
        migrations.RemoveField(
            model_name='books',
            name='pdf_prev',
        ),
        migrations.AddField(
            model_name='books',
            name='is_update_info',
            field=models.BooleanField(default=False, verbose_name='IS UPDATE INFO ONLY'),
        ),
        migrations.AddField(
            model_name='books',
            name='is_update_pdf',
            field=models.BooleanField(default=False, verbose_name='IS UPDATE ALL DATA?'),
        ),
        migrations.CreateModel(
            name='FeaturedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_active', models.BooleanField(default=True, verbose_name='IS ACTIVE?')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='literatur.books')),
            ],
        ),
        migrations.CreateModel(
            name='OnSaleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('is_active', models.BooleanField(default=True, verbose_name='IS ACTIVE?')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='literatur.books')),
            ],
        ),
    ]
