# Generated by Django 5.1.4 on 2024-12-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0011_remove_books_discount_remove_books_is_bestseller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='tipe',
        ),
    ]
