# Generated by Django 5.1.4 on 2024-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literatur', '0012_remove_books_tipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbook',
            name='body',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='featuredbook',
            name='header',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='onsalebook',
            name='body',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='onsalebook',
            name='header',
            field=models.CharField(default='', max_length=50),
        ),
    ]
